sudo apt-get remove \
baobab \
ca-certificates-java \
celluloid \
cheese \
cheese-common \
default-jre \
default-jre-headless \
drawing \
flatpak \
gnome-calculator \
gnome-calendar \
gnome-disk-utility \
gnome-screenshot \
gnome-system-monitor \
hexchat \
hexchat-common \
hypnotix \
liblibreoffice-java \
libreoffice-base \
libreoffice-base-core \
libreoffice-base-drivers \
libreoffice-calc \
libreoffice-common \
libreoffice-core \
libreoffice-draw \
libreoffice-gnome \
libreoffice-gtk3 \
libreoffice-help-common \
libreoffice-help-de \
libreoffice-help-en-gb \
libreoffice-help-en-us \
libreoffice-help-es \
libreoffice-help-fr \
libreoffice-help-it \
libreoffice-help-pt \
libreoffice-help-pt-br \
libreoffice-help-ru \
libreoffice-help-zh-cn \
libreoffice-help-zh-tw \
libreoffice-impress \
libreoffice-java-common \
libreoffice-l10n-de \
libreoffice-l10n-en-gb \
libreoffice-l10n-en-za \
libreoffice-l10n-es \
libreoffice-l10n-fr \
libreoffice-l10n-it \
libreoffice-l10n-pt \
libreoffice-l10n-pt-br \
libreoffice-l10n-ru \
libreoffice-l10n-zh-cn \
libreoffice-l10n-zh-tw \
libreoffice-math \
libreoffice-sdbc-hsqldb \
libreoffice-style-colibre \
libreoffice-writer \
onboard \
onboard-common \
openjdk-11-jre \
openjdk-11-jre-headless \
orca \
pix \
pix-data \
pix-dbg \
python3-uno \
redshift \
redshift-gtk \
rhythmbox \
rhythmbox-data \
rhythmbox-plugins \
rhythmbox-plugin-tray-icon \
simple-scan \
sticky \
thingy \
thunderbird \
thunderbird-gnome-support \
timeshift \
transmission-common \
transmission-gtk \
warpinator \
webapp-manager \
youtube-dl
